### ISSUE TITLE
Use geocoder gem instead of geokit

### ISSUE THREAD

**Issue by giladgray** [giladgray/WhichBus#15]
https://github.com/alexreisner/geocoder
It looks much simpler and more reliable than Geokit. Also it's designed for Rails 3.

**Comment by daveremy** [comment]
Looks cool.

-----Original Message-----
From: Gilad Gray [mailto:reply@reply.github.com] 
Sent: Wednesday, January 18, 2012 1:37 AM
To: daveremy
Subject: [WhichBus] Use geocoder gem instead of geokit (#15)

https://github.com/alexreisner/geocoder
It looks much simpler and more reliable than Geokit. Also it's designed for Rails 3.

---

Reply to this email directly or view it on GitHub:
https://github.com/giladgray/WhichBus/issues/15
