### ISSUE TITLE
times are showing up weird on the right column (3AM?) 

### ISSUE THREAD

**Issue by kimmanis** [giladgray/WhichBus#22]

**Comment by giladgray** [comment]
I figured it out! Just added a little debug output and the problem popped right up: The whole -15300d thing happens when predicted times are 0, as in "no prediction." So we'll have to check that case and display scheduled time when there is no prediction. We'll probably also want to give the user a little notification that there is no prediction at the moment.

**Comment by giladgray** [comment]
fixed this for the most part! now if no prediction is given, the UI will display scheduled arrival time instead. just need to get the text color working correctly.
